/* This file was automatically generated by ./configure */
#ifndef _CONFIGURE_H_
#define _CONFIGURE_H_

#define CONFIGURE_NAME      "ini"
#define CONFIGURE_VERSION   "0.1.0"
#define CONFIGURE_ARCH      "x86_64"
#define CONFIGURE_STDIO 1
#define CONFIGURE_STDLIB 1
#define CONFIGURE_STRING 1
#define CONFIGURE_CTYPE 1
#define CONFIGURE_ISBLANK 1
#define CONFIGURE_GETC 1
#define CONFIGURE_UNGETC 1
#define CONFIGURE_MEMSET 1

#endif